spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/issueabroad
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug